NumPy - один из самых важных пакетов для работы с числовыми данными. 

Многие пакеты  используют NumPy в качестве стандартного интерфейса для обмена данными.

Ключевые концепции NumPy
-  Разработан для эффективной работы с многомерными данными
-  Хранит данные в связанных блоках памяти. Ядро NumPy реализовано на C что позволяет эффективно упоавлять памятью.
-  Поддерживает распараллеливание работы с многомерными массивами.

## Установка

In [1]:
! pip install numpy

Импорт пакета:

In [2]:
import numpy as np

Проверка текущей версии:

In [3]:
print(np.__version__)

2.2.4


## Создание многомерных массивов в NumPy

Основным объектом в NumPy является многомерный массив (ndarray) являющейся гибким контейнером для больших наборов данных. 

ndarray является многомерным контейнером для гомогенных данных. 
Это значит что все элементы массива должны быть одного типа.
Каждый объект типа ndarray характеризуется: формой, размерами размерностей и типом.

### Создание массива

In [13]:
data = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr = np.array(data)
arr


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr.ndim

2

In [15]:
arr.shape

(2, 4)

In [16]:
arr.dtype

dtype('int64')

## Создание массивов в NumPy

### Другие возможные способы создания 

In [18]:
np.zeros((2,3)) # Инициализация нулями

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((2,3)) # Инициализация еденицами

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(5) #Еденичная матрица

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Задание типа

In [24]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [25]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3], dtype=int32)

### Преобразование типов

In [28]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
float_array = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
float_array

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [31]:
int_array = int_array.astype(float_array.dtype)
int_array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Арифметика

In [32]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
arr * arr # Поэлементное умножение

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
arr - arr # Поэлементное вычитание

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
arr + arr # Поэлементное сложение

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [36]:
1 / arr # Деление числа на скаляр

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [38]:
arr / arr #Поэлементное деление

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
arr ** 2 #Степень

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [40]:
arr1 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2 = np.array([[0., 4., -1.], [7., -2., -12.]])
arr1 > arr2

array([[False, False,  True],
       [False,  True,  True]])

### Индексация и слайсинг

In [41]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5] # Доступ по индексу

np.int64(5)

In [45]:
arr[2:5] #Срез

array([2, 3, 4])

In [47]:
arr[2:5] = 20 # Присвоение
arr 

array([ 0,  1, 20, 20, 20,  5,  6,  7,  8,  9])

In [ ]:
#По умолчанию NumPy оперирует ссылками. Это сделано для эффективоного управления памятью

In [ ]:
arr_slice = arr[5:8] 
arr_slice[:] = 64
arr


array([ 0,  1, 20, 20, 20, 64, 64, 64,  8,  9])

In [ ]:
arr_slice = arr[5:8].copy() #Создаем копию объекта в памяти
arr_slice[:] = 64
arr

array([ 0,  1, 20, 20, 20, 64, 64, 64,  8,  9])